### ISSUE TITLE
Error compiling 4.19 kernel

### ISSUE THREAD

**Issue by skillbill74** [wxt1221/KernelSU#8]
### Please check before submitting an issue

- [X] I have searched the issues and haven't found anything relevant
- [X] I will upload bugreport file in KernelSU Manager - Settings - Report log
- [X] I know how to reproduce the issue which may not be specific to my device

### Describe the bug

While switching to wxt1221 from a modified tiann KernelSU with the patches for non-GKI from here:https://github.com/tiann/KernelSU/discussions/955#discussioncomment-7617166
I am unable to compile my 4.19 kernel. I have patched namespace.c and it worked with 0.7.5 tiann before switching.

Error:
   CC      drivers/kernelsu/core_hook.o
/home/runner/work/xiaomi-kernel-env/xiaomi-kernel-env/private/msm-google/drivers/kernelsu/core_hook.c:37:36: warning: declaration of 'struct mount' will not be visible outside of this function [-Wvisibility]
extern inline int check_mnt(struct mount *mnt);
                                   ^
/home/runner/work/xiaomi-kernel-env/xiaomi-kernel-env/private/msm-google/drivers/kernelsu/core_hook.c:38:37: warning: declaration of 'struct mount' will not be visible outside of this function [-Wvisibility]
extern void mntput_no_expire(struct mount *mnt);
                                    ^
/home/runner/work/xiaomi-kernel-env/xiaomi-kernel-env/private/msm-google/drivers/kernelsu/core_hook.c:39:29: warning: declaration of 'struct mount' will not be visible outside of this function [-Wvisibility]
extern int do_umount(struct mount *mnt, int flags);
                            ^
/home/runner/work/xiaomi-kernel-env/xiaomi-kernel-env/private/msm-google/drivers/kernelsu/core_hook.c:50:17: error: incompatible pointer types passing 'struct mount *' to parameter of type 'struct mount *' [-Werror,-Wincompatible-pointer-types]
        if (!check_mnt(mnt))
                       ^~~
/home/runner/work/xiaomi-kernel-env/xiaomi-kernel-env/private/msm-google/drivers/kernelsu/core_hook.c:37:43: note: passing argument to parameter 'mnt' here
extern inline int check_mnt(struct mount *mnt);
                                          ^
/home/runner/work/xiaomi-kernel-env/xiaomi-kernel-env/private/msm-google/drivers/kernelsu/core_hook.c:52:9: error: incomplete definition of type 'struct mount'
        if (mnt->mnt.mnt_flags & MNT_LOCKED) /* Check optimistically */
            ~~~^
/home/runner/work/xiaomi-kernel-env/xiaomi-kernel-env/private/msm-google/drivers/kernelsu/core_hook.c:44:9: note: forward declaration of 'struct mount'
        struct mount *mnt = real_mount(path->mnt);
               ^
/home/runner/work/xiaomi-kernel-env/xiaomi-kernel-env/private/msm-google/drivers/kernelsu/core_hook.c:64:19: error: incompatible pointer types passing 'struct mount *' to parameter of type 'struct mount *' [-Werror,-Wincompatible-pointer-types]
                ret = do_umount(mnt, flags);
                                ^~~
/home/runner/work/xiaomi-kernel-env/xiaomi-kernel-env/private/msm-google/drivers/kernelsu/core_hook.c:39:36: note: passing argument to parameter 'mnt' here
extern int do_umount(struct mount *mnt, int flags);
                                   ^
/home/runner/work/xiaomi-kernel-env/xiaomi-kernel-env/private/msm-google/drivers/kernelsu/core_hook.c:68:19: error: incompatible pointer types passing 'struct mount *' to parameter of type 'struct mount *' [-Werror,-Wincompatible-pointer-types]
        mntput_no_expire(mnt);
                         ^~~
/home/runner/work/xiaomi-kernel-env/xiaomi-kernel-env/private/msm-google/drivers/kernelsu/core_hook.c:38:44: note: passing argument to parameter 'mnt' here
extern void mntput_no_expire(struct mount *mnt);
                                           ^
3 warnings and 4 errors generated.

Any help appriciated.

### To Reproduce

_No response_

### Expected behavior

_No response_

### Screenshots

_No response_

### Logs

_No response_

### Device info

- Device: Alioth
- OS Version: 14
- KernelSU Version: 0.7.6
- Kernel Version: 4.19.246


### Additional context

_No response_

**Comment by skillbill74** [comment]
this import might be missing from kernel/core_hook.c
#include "../../fs/mount.h"

**Comment by wxt1221** [comment]
https://github.com/wxt1221/android_kernel_oneplus_sdm845/commit/70ace81f14c97cf7896eb09c1f5a3c02a5f012ea#diff-26b064824bfafef546f17235dc1f34dbea87ce6c27f9320b5d4427bfa4d2b0e9

**Comment by wxt1221** [comment]
That's not neccessary. Because I define these symbols by extern

**Comment by skillbill74** [comment]
> That's not neccessary. Because I define these symbols by extern

@wxt1221 Thank you, can you please point where those are defined?
From the errors I am encountering from the first post, it seems the "struct mount" has no definition defined.
Adding #include "../../fs/mount.h" solves the issue.

In your kernel for sdm845 the submodule is pointing to 6bebe7347fad0eb4b0a57cadf1e80d00d56edcdb that is not visible to me or does not exist, so I cannot see which version is used.

Can we keep the issue open? others might benefit if facing similar issues
